name: Deploy to staging

on: 
  push:
    branches:
      - develop
jobs:
  deploy:
    uses: ./.github/workflows/_build_deploy.yml
    with:
      ckb-mode: testnet
      api-url: ${{ secrets.STAGING_API_URL }}
      k8s-namespace: staging
      k8s-workload: ckb-explorer-front
    secrets: inherit
