name: Deploy to staging

on: 
  push:
    branches:
      - develop
jobs:
  deploy:
    uses: ./.github/workflows/_build_deploy.yml
    with:
      ckb-mode: testnet
      k8s-namespace: staging
      k8s-workload: ckb-explorer-front
      environment: staging
    secrets: inherit
